myblog/blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.IndexPage.as_view()),
    path('<int:pk>/', views.PublicationPage.as_view()),
    path('review/<int:pk>/', views.AddComment.as_view(), name='add_comment'),
    path('<int:pk>/add_like', views.AddLike.as_view(), name='add_like'),
    path('<int:pk>/del_like', views.DelLike.as_view(), name='del_like'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/models.py
from django.db import models


class Publication(models.Model):
    """Publication data"""

    title = models.CharField('header', max_length=100)
    description = models.TextField('text')
    author = models.CharField('author', max_length=100)
    date = models.DateField('date')
    image = models.ImageField('image', upload_to='image/%Y')

    def __str__(self):
        return f"{self.title}, {self.author}"

    class Meta:
        verbose_name = 'Publication'
        verbose_name_plural = 'Publications'


class Comment(models.Model):
    """Comments"""

    email = models.EmailField()
    name = models.CharField('Name', max_length=50)
    text = models.TextField('Text', max_length=2000)
    publication = models.ForeignKey(Publication, verbose_name='Publication', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'


class Like(models.Model):
    """Likes"""

    ip_address = models.CharField('IP-address', max_length=20)
    publication = models.ForeignKey(Publication, verbose_name='Publication', on_delete=models.CASCADE)

myblog/blog/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic.base import View
from .models import Publication
from .models import Like

from .form import CommentForm


# noinspection PyMethodMayBeStatic
class IndexPage(View):
    """Publications view"""

    def get(self, request):
        """

        :param request:
        :return:
        """
        publications = Publication.objects.all()

        return render(request, 'blog/blog.html', {'publication_list': publications})


# noinspection PyMethodMayBeStatic
class PublicationPage(View):
    """Publication view"""

    def get(self, request, pk):
        publication = Publication.objects.get(id=pk)
        return render(request, 'blog/publication.html', {'publication': publication})


# noinspection PyMethodMayBeStatic
class AddComment(View):
    """Leaving comments"""

    def post(self, request, pk):
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.publication_id = pk
            form.save()

        return redirect(f'/{pk}')


class AddLike(View):
    """Add like to publication"""

    # noinspection PyMethodMayBeStatic
    def get(self, request, pk):
        client_ip = get_client_ip(request)
        try:
            Like.objects.get(ip_address=client_ip, publication_id=pk)
        except Like.DoesNotExist:
            like = Like()
            like.ip_address = client_ip
            like.publication_id = pk
            like.save()

        return redirect(f'/{pk}')


class DelLike(View):
    """Like deletion"""

    # noinspection PyMethodMayBeStatic
    def get(self, request, pk):
        client_ip = get_client_ip(request)
        try:
            like = Like.objects.get(ip_address=client_ip)
            like.delete()
        except Like.DoesNotExist:
            pass

        return redirect(f'/{pk}')


# Util methods
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

myblog/templates/blog/blog.html
<!DOCTYPE>
{% load static %}
<html  lang="en">
<head>
	<title>My blog</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

{#	<link rel="shortcut icon" href="{% static 'css/images/favicon.ico' %}" />#}

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Main</a></li>
			    <li><a href="/admin">Admin panel</a></li>
			    
			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">
				
				<div class="projects">
					<h3>Records</h3>
                    {% for publication in publication_list %}
					<div class="item">
						<div class="image left">
							<a href="#"><img src="{{ publication.image.url }}" width="200px" alt="" /></a>
						</div>
						<div class="text left">
                            <h4><a href="{{ publication.id }}">{{ publication.title }}</a></h4>
							<p>{{ publicatrion.description }}</p>
							<p>Author: {{ publication.author }} </p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
                    {% endfor %}
					
				</div>
			</div>
			
			<div class="cl">&nbsp;</div>
		</div>
		

	</div>
	
	<div id="footer">
		<p class="copy right">Copyright &copy;  2023 </p>
	</div>
</div>
</body>
</html>

myblog/templates/blog/blog_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mini-blog</title>
</head>
<body>
    {% for publication in publication_list %}
        <h3>{{ publication.title }}</h3>
        <p>{{ publication.description }}</p>
        <p>{{ publication.author }}</p>
    {% endfor %}
</body>
</html>

myblog/templates/blog/publication.html
<!DOCTYPE>
{% load static %}
<html  lang="en">
<head>
	<title>My blog</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />

{#	<link rel="shortcut icon" href="{% static 'css/images/favicon.ico' %}" />#}

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Main</a></li>
			    <li><a href="/admin">Admin panel</a></li>

			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h3>{{ publication.title }}</h3>
                    <p align="center">
                        <img src="{{ publication.image.url }}" width="50%" alt="" />
                    </p>
					<div class="item">
						<div class="text left">
							<p>{{ publicatrion.description }}</p>
							<p>Author: {{ publication.author }} </p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>

				</div>
			</div>
            <div>
                <br>
                <p>Likes: {{ publication.like_set.all.count }}</p>
                <br>
                <a href="{% url 'add_like' publication.id %}">Like</a>
                <a href="{% url 'del_like' publication.id %}">Dislike</a>
            </div>
            <div class="form-comment">
                <h3>Leave comment</h3>
                <div>
                    <form action="{% url 'add_comment' publication.id %}" method="post">
                        {% csrf_token %}
                        <div>
                            <label>Your comment
                                <textarea name="text"></textarea>
                            </label>
                        </div>
                        <div>
                            <label>Your name *
                                <input type="text" name="name">
                            </label>
                        </div>
                        <div>
                            <label>Email *
                                <input type="email" name="email">
                            </label>
                            <br>
                            <input type="submit">
                        </div>
                    </form>
                </div>
            </div>
            <div>
                {% for comment in publication.comment_set.all %}
                <div class="view-comment">
                    <h4>{{ comment.name }}</h4>
                    <p>
                        {{ comment.text }}
                    </p>
                </div>
                {% endfor %}
            </div>

			<div class="cl">&nbsp;</div>
		</div>


	</div>

	<div id="footer">
		<p class="copy right">Copyright &copy;  2023 </p>
	</div>
</div>
</body>
</html>